version: 2

models: 
    - name: fct_orders
      description: "TABELA FATO PEDIDOS"
      columns:
        - name: order_id
          description: "A chave primária original da tabela"
          tests:
            - unique
            - not_null


    - name: dim_customers
      description: "DIMENSÃO CLIENTES (PEDIDOS POR CLIENTE)"
      columns: 
        - name: customer_id
          description: "A chave primária original da tabela"  
          tests:
            - unique
            - not_null

    - name: dim_products
      description: "DIMENSÃO PRODUTOS (PEDIDOS POR PRODUTO)"
      columns: 
        - name: product_id
          description: "A chave primária original da tabela"  
          tests:
            - not_null